### PR TITLE
Adding new Thieving Magpie subclass homebrew

### PR DESCRIPTION
**Pull request by TwoHeadedBoy**
I wrote up a Subclass script for this content:

http://firebringeraxels-junk.tumblr.com/post/162875990845/the-thieving-magpie-a-rogue-that-works-in-unison

it's a Roguish Archetype called the Thieving Magpie.

### CODE REVIEW

**Comment by morepurplemorebetter** [comment]
Thank you for this addition!

One thing that is not essential for the code to work, but that I do consider essential for the code to be included in the Fan-made Additions Dropbox, is the way the descriptions for the class features are written. What I did for the class features for all the classes and archetypes included in the sheet, and fan-made additions currently available, are the following things:
- Use the first person (so replace 'you' with 'I');
- Use capitalization only for the ability scores (Str, Dex, Con, Int, Wis, Cha), skills (e.g. Perception, Investigation, etc.), and spells (e.g. Identify, Magic Missile, etc.);
- Not have any overflowing sentences on the sheet. This means that the description is cut into sentences that each fit onto a single line in the "Class Features" section of a Colourful sheet (the Printer-Friendly version has more space in the Class Features section). Each of the lines start with three spaces, hence the " + "\n    " + " in the examples.
[this is a list I send everybody, so not all three points might be applicable to your situation]

Also, I think it would be best to add the link to the source of the archetype as [a SourceList entry](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content%20syntax/Homebrew%20Syntax%20-%20SourceList.js).

**Comment by TwoHeadedBoy** [comment]
Thanks for your comments, @morepurplemorebetter ! I have a few questions:
Can I get an approximate number of characters that fit on a line of the Class Features section? I'd like to be accurate as I break up the descriptions.
When I submit my revision, can I count on a review of my SourceList entry? I'm not sure I'm following the syntax or conventions.

**Comment by morepurplemorebetter** [comment]
I'm happy to review your code once you think it is up to the task :)

You can find [the syntax for adding a source](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content%20syntax/Homebrew%20Syntax%20-%20SourceList.js) at [the same place as all the other explanatory syntax files](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/tree/master/additional%20content%20syntax).

There is no hard character limit for a line in the Class Features section, because the sheet doen't use uni-width fonts (those are ugly). Instead, you will have to test your descriptions in the Class Features section of [the Colourful version of the character sheet](https://www.dmsguild.com/product/193053/Character-Sheet--MPMBs-fullyautomated-Colorful-character-generator).

**Comment by morepurplemorebetter** [comment]
I made some corrections to your code and [added it to the Additional Content folder](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Subclass%20-%20Rogue%20(Thieving%20Magpie)%20%5BFirebringeraxel's%20work%2C%20transcribed%20by%20TwoHeadedBoy%5D.js). Thank you very much for this addition.

I ended up re-doing most of the descriptions to make them better fit with the other things of the sheet. I also condensed the Slippery As A Snake feature to a single entry because otherwise not all the class features of a level 20 Thieving Magpie would fit in the Class Features section of the sheet.

**Comment by TwoHeadedBoy** [comment]
Thanks so much! I appreciate it!

**Pull request closed without merging**
