### PR TITLE
Create Merfolk Erectus [by Snutze].js

### PR DESCRIPTION
**Pull request by Snutze**
Hey I hope this one reach you

### CODE REVIEW

**Comment by Snutze** [comment]
I submitted a new one getting the other version was confusing for the original

**Comment by morepurplemorebetter** [comment]
Ah, I see now why the other pull request didn't get updated. You didn't update the file, but instead made a new branch. You now have 4 branches for this repo: 'master', 'patch-1', 'Snutze-patch-1', and 'patch-2'. You can see your branches [here](https://github.com/Snutze/MPMBs-Character-Record-Sheet/branches).

[Your original pull request](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/pull/55) was done from branch 'patch-1', while this pull request is from branch 'patch-2'. It would be easier if you just stick with one branch and update the file there, but I guess that was your intention all along ;)

Anyway, about the code itself, I'm still missing the comment header explaining what this is.

Furthermore:

1. Does the race get darkvision 60 ft on land and darkvision 120 ft underwater? Because that is not at all clear from the racial traits or the fact that it gets a sense named "Underwater 120 ft". Is the sense "Underwater" related to darkvision, or am I misunderstanding? Or do you mean it like an alternative to termorsense or something?
2. The object name needs to be all lowercase.
3. Why is the swim speed reduced to 15 ft while encumbered? Normally, encumbrance reduces speed by 10 ft.

I made a Gist to show you what I would change: https://gist.github.com/morepurplemorebetter/6bc5e06b33313a4a9d66dacdbd83ad76

**Comment by Snutze** [comment]
Okay so everything you did is good
About Darkvision its 60ft, the underwater 120ft is just to indicate they can see at 120ft underwater where for most creature it would be very blurry within a few feets. If the underwater is liek darkness then the darkvision 60ft would simply apply

**Comment by Snutze** [comment]
vision : [["Darkvision", 60], ["Citizen of the Sea (Vision is not affected by water)", 0]] does that make mroe sense ?

**Comment by Snutze** [comment]
There this time I did my commit on the existign branch and version

**Comment by Snutze** [comment]
image

I just tested it works great but for the saving throw/dis field is there a way to force a break if it comme from 2 sources ? woudl starting the description with /n works ?  (same with vision)

**Comment by Snutze** [comment]
hahahaha YES I was somehwo struggling shortenign it , you rock XD

**Comment by Snutze** [comment]
Watervision: See clearly Underwater

**Comment by Snutze** [comment]
there we go, ( I also did thebreak manually so agree it makes more sense

**Comment by morepurplemorebetter** [comment]
Unless you define "Watervision" somewhere else, I don't think it adds anything to name it that. I now added this to the main repository, [see here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Races/Merfolk%20Erectus%20%5Bby%20Snutze%5D.js).

Thank you very much for the addition!

**Pull request closed without merging**
