### PR TITLE
Applied a linter to the code to clean things up some.  

### PR DESCRIPTION
**Pull request by erickrause**
https://standardjs.com/ then just ran standard --fix

Basically spaces instead of tabs.
no semi colons.
Single quotes when able.

Then I modified this gist and ran it against what was left to replace the tabs with spaces.
https://gist.github.com/bluefuton/1468061

### CODE REVIEW

**Comment by morepurplemorebetter** [comment]
Thanks but no thanks. I like using tabs, semicolons and double quotes for my strings. I'm still a bit of a novice to coding, so I might be wrong, but aren't semicolons necessary at the end of a var statement, when removing line breaks? Because Acrobat is not so good at keeping line breaks in code.

Your changes also break the syntax files...

**Comment by erickrause** [comment]
I'll have to check how they might have broken the syntax files.
I don't think semi colons are required anywhere.  Unless maybe having multiple statements on one line.  But I let the linter do all of the semi colons and quotes.  I just cleaned up some tabs manually.
The issue with tabs is that they can be represented differently based on the file editor.  So people have just consolidated by replacing them with tabs.  There is even a way to do this in Notepad++.

No worries on not accepting the changes.  I'll just turn the linter off while working on your project.

**Comment by morepurplemorebetter** [comment]
Acrobat sometimes does remove line breaks from code, so that is why the semicolons are important. They probably aren't necessary everywhere I'm using them, though, but I don't know enough to know where they are and aren't ;)

**Comment by jrhoades93** [comment]
semicolons are a good habit to keep as other languages (if you ever decide to try new languages) require them. Plus it just makes code look nice and easier to read in my opinion

**Comment by erickrause** [comment]
What other new-ish languages require semi colons?
C# still does.  I normally code in Ruby on Rails, which doesn't.  (It does in some cases when you want to have multiple logical statements on one line)  Just looked, Python doesn't.  Javascript kind of does, but mostly doesn't.

Personally, I find that semi colons are just more things to type rather than help me speed up development or express my intent in code.

**Comment by jrhoades93** [comment]
Languages that I use all require it C#, Java, C++, RPG (this one is for work only). I work to keep up the good habit by just adding semicolons unless it is going to cause problems

**Comment by RobRoseKnows** [comment]
JavaScript doesn't enforce semicolon usage but it's best to use them as there are cases where a lack of a semicolon will break things quietly.

**Pull request closed without merging**
