### PR TITLE
Fixing Martial Arts wording

### PR DESCRIPTION
**Pull request by Shwaffle**
PHB 78 says "and monk weapons, which are shortswords and any simple melee weapons that don't have the two-handed or heavy property."

Reported by /u/Anthoux on /r/mpmb

### CODE REVIEW

**Comment by RobRoseKnows** [comment]
Is it the same in the SRD?

**Comment by morepurplemorebetter** [comment]
Unfortunately, with this change the wording won't fit on a single line in the Class Features section.

I'm open for suggestions how to change it so that it includes the melee denominator and still fits on a single line of the Class Features section of the Colourful sheets. As long as there is no convoluted use of abbreviations that aren't used anywhere else in the texts.

Making it two lines is also not an option, because the monk is already cramped for space and a level 20 monk uses every line of the Class Features section.

**Comment by Shwaffle** [comment]
I do tend to forget about the colorful sheet! I should try it out and see if I like the layout better.

Perhaps change to 2H for two-handed? I'm unsure if it's used elsewhere, but for this case I think it's something a large majority of players would understand the meaning of.

image

**Comment by morepurplemorebetter** [comment]
2H is the type of abbreviation that I was talking about, convoluted and not used anywhere else.
I have decided to go for something else, as suggested on reddit:

    "Monk weapons: any simple melee (not two-handed/heavy), unarmed strike, shortsword"

It is part of [this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/4840cd4fd80123125f92afe44428eafc32213522) and I will thus be closing this pull request. Thank you for bringing this to my attention and thinking with me for a solution!

**Pull request closed without merging**
