### PR TITLE
Update Order of the Lycan to 1.5

### PR DESCRIPTION
**Pull request by Smashman**
I tried to add auto calculation of the Lycan Regeneration hit point amount, however it was not updating whenever I updated the Con mod. Is there a way to do so?

### CODE REVIEW

**Comment by Smashman** [comment]
Changelog for comparison:

1) Changed Blood Lust to be more in line with concentration checks, and be a little more dangerous when taking bigger hits of damage! I mean, whats the point of this option if you're afraid of losing control every now and again. ;) However, when you do go berserk, you do regain control after the attack action, allowing a Bonus Action and the remainder of your movement to be of use that turn.

2) Feral Precision changed to Beastly Precision (just for my own titling preference), and now increases unarmed attacked by half of your proficiency bonus (to allow a progression on par with magical weapons of a +3 variety at higher levels). 

3) Removed Improved Resilient Hide, as the resistance element required the PC to choose a rite that would many times be up against foes resistant or immune to it, lessening the fun of the feature. Instead, I've introduced Lycan Regeneration to replace it, which is largely more useful and very much in theme with the Hybrid form.

4) Blood Curse of the Howl has been improved to affect any number of targets you choose in 30 feet, only it causes fear on a failed save, and stun on failing by 5 or more. Amplifying increases the radius to 60 ft.

**Comment by Smashman** [comment]
Ah, looks like there's been a Blood Hunter update too. 
I'll investigate soon.

**Comment by jrhoades93** [comment]
Hey man, just wanted to say thanks for keeping these up to date.

**Comment by Smashman** [comment]
Going to work on the Blood Hunter changes and then open a new PR

**Comment by morepurplemorebetter** [comment]
Note that I just updated the Blood Hunter and Order of the Lycan to their latest versions, [see the code here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Classes/Blood%20Hunter%20%5BMatthew%20Mercer's%20work%2C%20transcribed%20by%20Darryl%20%26%20MPMB%5D.js).

**Comment by Smashman** [comment]
Fair enough, apologies for dragging it out.
Perhaps we should use the issue system to take some of the work off of you updating these things?

**Comment by morepurplemorebetter** [comment]
It would already be very helpful if an issue was opened when something is updated. I simply don't have the time to keep track of all the different sources if/when they might have an update.

And even then, most of them don't have a changelog or anything, making it a very time-consuming job to even find out what has changed...

**Pull request closed without merging**
