### PR TITLE
Fix description of Wall of Fire

### PR DESCRIPTION
**Pull request by BraabHimself**
Update description of Wall of Fire to say "thin" instead of "think".

### CODE REVIEW

**Comment by morepurplemorebetter** [comment]
Thank you for pointing out this mistake! Your change is however not in line with what the PHB says. It should be "thick", not "thin".

Also, your file seems to have every line changed, not just the description of Wall of Fire. Probably something to do with a beautifier script?

**Comment by BraabHimself** [comment]
Ah dang, I thought I'd do is this way instead of posting a bug on
reddit/github.

I thought the diff looked weird, but I had chalked it up to the diff tool.
I used Visual Studio Code (second time using it), to fix it, so it may have
something to do with that.

**Comment by morepurplemorebetter** [comment]
I edited your comment on GitHub to remove some identifying information at the bottom.
As it is much easier for me, I will be closing this pull request and make the necessary changes to the Wall of Fire. The downside of this is that you won't be listed as contributing to this repo, if that is okay with you.

**Comment by BraabHimself** [comment]
That's cool with me. Just glad I was able to make the sheet a tiny bit
better in some way!

**Comment by morepurplemorebetter** [comment]
Okay great, it is now fixed in commit 0891ee45e501200102978af062cd1817a5ea2b0b

**Pull request closed without merging**
