### PR TITLE
Merfolk Erectus.js

### PR DESCRIPTION
**Pull request by Snutze**
Playable Merfolk that learned to walk on land

### CODE REVIEW

**Comment by morepurplemorebetter** [comment]
Can I assume this is a race you made yourself, as you list the source as "HB"?

Your file name is missing an extension. Add .js to it to get JavaScript highlighting.

Your script ends with three unnecessary closing brackets '}' which will cause it to produce an error. You really only need one closing bracket per opening bracket, or JavaScript will throw a fit ;) The rest of the script seems fine.

Did you already test the script to see if it works? 

You have a lot of features that only work while underwater, so you might make that clear in the other places of the sheet than the racial traits section.
For example, you could make it `vision: [["Darkvision (underwater)", 60],` and `dmgres: [["Cold", "Cold (underwater)"]],`.

You can add the lightning vulnerability to the save area:
`savetxt ; {
    text : ["Vulnerable to Lightning while underwater"],
},`

In the racial trait text, on line 25, you might want to put a line break and three spaces `"\n   "` between the closing bracket and 'Amphibious'.

I'm happy to add this race to my GitHub if you fix the above issues and add [the comment header that you can find with all other addition-scripts](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Races/Merfolk%2C%20with%204%20subraces%20%5Bby%20Sarixis%5D.js#L1-L14).

**Comment by Snutze** [comment]
hahahaha XD ok and I did the tweaks as recommended ( except for few details, I made underwater its own item which synergize with darkvision and the cold vun is always so I didnt define water

**Comment by Snutze** [comment]
Man I suck with GitHub ( first time really using it )

**Comment by morepurplemorebetter** [comment]
I can't see any changes to the file. I'm also not an experienced GitHub user, especially when it comes to pull requests, but it might be that you would have to make a new pull request if you change anything on the file. All I can see is the initial pull request. I'm happy to take a look at the code to see if it is all working now if you just post a link to it. Looking at your GitHub fork, I can't see any changes to the file either. Might it be that you didn't commit/push any changes and they are just on your machine? Or are they publicly accessible somewhere else? All I can find is [this file](https://github.com/Snutze/MPMBs-Character-Record-Sheet/blob/f61eda9860fefc96deb73298021ecee149ee47ba/additional%20content/Races/Merfolk%20Erectus) which is linked to this commit.

**Pull request closed without merging**
